name: explore-extensions
channels:
  - conda-forge
dependencies:
  - python==3.11
  - jupyter
  - matplotlib
  - nbstripout
  - numpy
  - pandas
  - pooch
  - tqdm
  - xarray
  - pip
  - pip:
    - git+ssh://git@github.com/OMS-NetZero/FAIR.git@v2.2-dev
    # install development version of fair-2.2 that grabs emissions from 
    # pre-supplied CSVs
